# Generated by Django 5.0.6 on 2024-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='calendar_type',
            field=models.CharField(default='Malibu', max_length=50),
            preserve_default=False,
        ),
    ]
