# Generated by Django 5.0.6 on 2024-07-01 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0003_remove_booking_created_at_booking_calendar_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='calendar_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
