# Generated by Django 5.0.6 on 2024-07-01 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0004_remove_booking_calendar_type_booking_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
