# Generated by Django 5.0.6 on 2024-07-07 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0006_alter_booking_unique_together_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_type',
            field=models.CharField(choices=[('malibu', 'Calendar Malibu'), ('zuma', 'Calendar Zuma')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
