# Generated by Django 5.0.6 on 2024-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0011_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
