# Generated by Django 5.0.7 on 2024-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0006_alter_booking_unique_together_booking_calendar_type_and_more'),
        ('camper', '0014_booking_is_confirmed_alter_booking_is_active'),
    ]

    operations = [
    ]
