# Generated by Django 5.0.7 on 2024-07-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0015_merge_20240717_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
